### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danielsimig/dc_files/hyph_en_US.dic'

### ISSUE THREAD

**Issue by ethanjyx** [facebookresearch/text_characterization_toolkit#1]
hey, trying to run the repo to give it a shot, got this error

```
(text_characterization_toolkit) Ethans-MacBook-Pro:text_characterization_toolkit ethan$ python tools/compute.py -t "This is an example input text. It has a single paragraph and two sentences."
Loading spaCy..

Loading resource files..

Traceback (most recent call last):
  File "/Users/ethan/repos/text_characterization_toolkit/tools/compute.py", line 73, in <module>
    mp.load_resources()
  File "/Users/ethan/repos/text_characterization_toolkit/text_characterization/metrics.py", line 98, in load_resources
    metric_collection.load_resources()
  File "/Users/ethan/repos/text_characterization_toolkit/text_characterization/metrics.py", line 167, in load_resources
    self.hyphenator = Hyphenator(parse_filename_macros(hyphenator_dict_file))
  File "/Users/ethan/miniconda3/lib/python3.9/site-packages/hyphenator.py", line 200, in __init__
    _hdcache[filename] = HyphenationDictionary(filename)
  File "/Users/ethan/miniconda3/lib/python3.9/site-packages/hyphenator.py", line 104, in __init__
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danielsimig/dc_files/hyph_en_US.dic'
```

I have installed all the dependencies. Thanks

**Comment by nazar-chepliaka** [comment]
replace `/Users/danielsimig/dc_files` with `<DATA_DIR>` in **configs/default.json**
